services:
  - type: web
    name: videoframer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
